module.exports = {
  EVENT_SCHEDULE_TYPES: {
    INTERVIEW: "INTERVIEW",
    CUSTOM: 'CUSTOM',
    // OTHERS: 'OTHERS'
  },
  APPLICANT_INTERVIEW_STATUSES: {
    PENDING: "PENDING",
    COMPLETED: "COMPLETED",
  },
};
